name: Python Service Dev

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string

jobs:
  echo-service:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected service
        run: |
            echo "🛠 Running CI for service: ${{ inputs.service_path }} in dev"
