name: Python Service CI/CD

on:
  workflow_call:
    inputs:
      lint:
        description: 'Run lint'
        required: false
        type: boolean
        default: true
      unit_tests:
        description: 'Run unit tests'
        required: false
        type: boolean
        default: true
      security:
        description: 'Run security'
        required: false
        type: boolean
        default: true
      shared_dir:
        description: 'Shared folder prefix (e.g., core)'
        required: true
        type: string
      event_name:
        required: true
        type: string
      ref:
        required: true
        type: string
      base_ref:
        required: false
        type: string
      python_version:
        required: false
        type: string
        default: '3.10'

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.list.outputs.changed-directories }}
    steps:
      - uses: actions/checkout@v4

      - uses: sankichi92/list-changed-directories@v1.1.5
        id: list
        with:
          target-file: 'Dockerfile'
          common-dependency-paths: |
            ${{ inputs.shared_dir }}/**

  lint:
    if: ${{ inputs.lint }}
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    uses: Aeronous/cicd-template/.github/workflows/python-lint.yml@main
    with:
      event_name: ${{ inputs.event_name }}
      ref: ${{ inputs.ref }}
      base_ref: ${{ inputs.base_ref }}
      service_path: ${{ matrix.service }}
      services: ${{ needs.detect.outputs.services }}
      python_version: ${{ inputs.python_version }}

  unit-tests:

    if: ${{ inputs.unit_tests }}
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    uses: Aeronous/cicd-template/.github/workflows/python-unit-tests.yml@main
    with:
      event_name: ${{ inputs.event_name }}
      ref: ${{ inputs.ref }}
      base_ref: ${{ inputs.base_ref }}
      service_path: ${{ matrix.service }}
      services: ${{ needs.detect.outputs.services }}
      python_version: ${{ inputs.python_version }}

  security:
    if: ${{ inputs.security }}
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    runs-on: ubuntu-latest
    steps:
      - uses: Aeronous/cicd-template/.github/workflows/run-gitleaks.yml@main
        with:
          event_name: ${{ inputs.event_name }}
          ref: ${{ inputs.ref }}
          base_ref: ${{ inputs.base_ref }}
          service_path: ${{ matrix.service }}
          services: ${{ needs.detect.outputs.services }}